import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Poppins } from "next/font/google";
import Navbar from "@/Components/General/Navbar";
import Footer from "@/Components/General/Footer";
import { ClerkProvider } from "@clerk/nextjs";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Haleve | Agency who build inspirations for world.",
  description: "Generated by create next app",
};


export const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>

      <html lang="en">
        <body
          // ${geistSans.variable} ${geistMono.variable}
          className={` ${poppins.className} antialiased`}
        >

          <Navbar className="bg-none" />
          {children}
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
